# Offense count: 2
Lint/HandleExceptions:
  Exclude:
    - 'lib/foreman_xen/vnc_tunnel.rb'

# Offense count: 2
Lint/RescueException:
  Exclude:
    - 'lib/foreman_xen/vnc_tunnel.rb'

# Offense count: 2
Lint/ShadowingOuterLocalVariable:
  Exclude:
    - 'app/models/foreman_xen/xenserver.rb'

# Offense count: 2
# Cop supports --auto-correct.
Lint/UnusedBlockArgument:
  Exclude:
    - 'lib/foreman_xen/engine.rb'

# Offense count: 4
# Cop supports --auto-correct.
Lint/UnusedMethodArgument:
  Exclude:
    - 'app/models/concerns/fog_extensions/xenserver/server.rb'
    - 'app/models/foreman_xen/xenserver.rb'

# Offense count: 5
Lint/UselessAssignment:
  Exclude:
    - 'app/helpers/xen_compute_helper.rb'
    - 'lib/foreman_xen/vnc_tunnel.rb'

# Offense count: 16
Metrics/AbcSize:
  Max: 76

# Offense count: 2
Metrics/BlockNesting:
  Max: 4

# Offense count: 2
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 352

# Offense count: 4
Metrics/CyclomaticComplexity:
  Max: 23

# Offense count: 83
# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 120
  Exclude:
    - 'app/helpers/xen_compute_helper.rb'

# Offense count: 19
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 66

# Offense count: 7
Metrics/PerceivedComplexity:
  Max: 24

Rails/ActionFilter:
  Exclude:
    - 'app/controllers/foreman_xen/snapshots_controller.rb'
